version: '3.8'

services:
  json-server:
    image: clue/json-server
    container_name: angularBooks-json-server
    ports:
      - "3000:80"
    volumes:
      - ./db.json:/data/db.json
    command: -H 0.0.0.0 /data/db.json
  
  angular-app:
    build: .
    ports:
      - 4200:4200
    depends_on:
      - json-server